/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yQj5EgHap5q
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { useEffect, useState } from 'react'
import { selectedDate } from '../stores/date-picker-store'
import { useStore } from '@nanostores/react'
import { getTimetable } from '@/lib/utils'


/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
function timeLineItem(name: string, time: string, key: string) {
  return (
    <div className="relative grid gap-1 text-sm" key={key}>
      <div className="absolute left-0 top-1 z-10 aspect-square w-3 translate-x-[-29.5px] rounded-full bg-gray-900 dark:bg-gray-50" />
      <div className="text-lg font-bold">{name}</div>
      <div className="text-gray-500 dark:text-gray-400">{time}</div>
    </div>
  )
}

export function Timeline({tables}) {
  const $selectedDate = useStore(selectedDate)

  return (
    <div className="p-6 sm:p-10 sm:py-0">
      <div className="relative grid gap-10 pl-6 after:absolute after:inset-y-0 after:left-0 after:w-px after:bg-gray-500/20 dark:after:bg-gray-400/20">
        {getTimetable(tables,$selectedDate).map((item,index) => timeLineItem(item.name, item.time,index.toString()))}
      </div>
    </div>
  )
}
